### PR TITLE
Dependencies

### PR DESCRIPTION
**Pull request by icidasset**
Updates some dependencies, in particular `elm-css`.
Also exposes the `Slide` type alias.

Thanks for this library ✌️

### CODE REVIEW

**Comment by xarvh** [comment]
Thanks you @icidasset !
The `Slide` constructor is kept private intentionally, to help backwards compatibility http://package.elm-lang.org/help/design-guidelines#keep-tags-and-record-constructors-secret
If you remove that line, I will be happy to merge.

**Comment by icidasset** [comment]
Oh interesting, I removed it 👍

**Comment by icidasset** [comment]
Thanks!

**Comment by ghost** [comment]
Thanks for the contribution.

**Pull request merged**
