### PR TITLE
Added blackOnWhite style option as default

### PR DESCRIPTION
**Pull request by ghost**
Added blackOnWhite style option and made it the default.

### CODE REVIEW

**Comment by xarvh** [comment]
Thanks!
I'll merge it as soon as I have the time to test. =)

**Comment by ghost** [comment]
I'm giving a presentation on elm tomorrow using elm-slides. Will try to add other styles when I get the chance.

**Comment by xarvh** [comment]
Fantastic. I have one style I need to add myself. o_O

**Comment by xarvh** [comment]
I have some more styling stuff to do, then I'll publish the new package.

**Pull request merged**
